<?php


return [
    
    'CentralDashboardControllers@Dashboard' => 'general',
    'CentralDashboardControllers@changeLang' => 'general',
    'CentralDashboardControllers@changeTheme' => 'general',
    'CentralDashboardControllers@changeThemeToDefault' => 'general',
 
    
    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@sort' => 'sort-user',
    'UsersControllers@arrange' => 'sort-user',
    'UsersControllers@charts' => 'charts-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',
    'GroupsControllers@sort' => 'sort-group',
    'GroupsControllers@arrange' => 'sort-group',
    'GroupsControllers@charts' => 'charts-group',

    'BundleControllers@index' => 'list-bundles',
    'BundleControllers@edit' => 'edit-bundle',
    'BundleControllers@update' => 'edit-bundle',
    'BundleControllers@fastEdit' => 'edit-bundle',
    'BundleControllers@add' => 'add-bundle',
    'BundleControllers@create' => 'add-bundle',
    'BundleControllers@delete' => 'delete-bundle',
    'BundleControllers@arrange' => 'sort-bundle',
    'BundleControllers@sort' => 'sort-bundle',
    'BundleControllers@charts' => 'charts-bundle',

    'MembershipControllers@index' => 'list-memberships',
    'MembershipControllers@edit' => 'edit-membership',
    'MembershipControllers@update' => 'edit-membership',
    'MembershipControllers@fastEdit' => 'edit-membership',
    'MembershipControllers@add' => 'add-membership',
    'MembershipControllers@create' => 'add-membership',
    'MembershipControllers@delete' => 'delete-membership',
    'MembershipControllers@arrange' => 'sort-membership',
    'MembershipControllers@sort' => 'sort-membership',
    'MembershipControllers@charts' => 'charts-membership',

    'FeatureControllers@index' => 'list-features',
    'FeatureControllers@edit' => 'edit-feature',
    'FeatureControllers@update' => 'edit-feature',
    'FeatureControllers@fastEdit' => 'edit-feature',
    'FeatureControllers@add' => 'add-feature',
    'FeatureControllers@create' => 'add-feature',
    'FeatureControllers@delete' => 'delete-feature',
    'FeatureControllers@arrange' => 'sort-feature',
    'FeatureControllers@sort' => 'sort-feature',
    'FeatureControllers@charts' => 'charts-feature',

    'AddonsControllers@index' => 'list-addons',
    'AddonsControllers@edit' => 'edit-addon',
    'AddonsControllers@update' => 'edit-addon',
    'AddonsControllers@fastEdit' => 'edit-addon',
    'AddonsControllers@add' => 'add-addon',
    'AddonsControllers@create' => 'add-addon',
    'AddonsControllers@delete' => 'delete-addon',
    'AddonsControllers@arrange' => 'sort-addon',
    'AddonsControllers@sort' => 'sort-addon',
    'AddonsControllers@charts' => 'charts-addon',

    'ExtraQuotaControllers@index' => 'list-extraQuotas',
    'ExtraQuotaControllers@edit' => 'edit-extraQuota',
    'ExtraQuotaControllers@update' => 'edit-extraQuota',
    'ExtraQuotaControllers@fastEdit' => 'edit-extraQuota',
    'ExtraQuotaControllers@add' => 'add-extraQuota',
    'ExtraQuotaControllers@create' => 'add-extraQuota',
    'ExtraQuotaControllers@delete' => 'delete-extraQuota',
    'ExtraQuotaControllers@arrange' => 'sort-extraQuota',
    'ExtraQuotaControllers@sort' => 'sort-extraQuota',
    'ExtraQuotaControllers@charts' => 'charts-extraQuota',

    'FAQControllers@index' => 'list-faqs',
    'FAQControllers@edit' => 'edit-faq',
    'FAQControllers@update' => 'edit-faq',
    'FAQControllers@fastEdit' => 'edit-faq',
    'FAQControllers@add' => 'add-faq',
    'FAQControllers@create' => 'add-faq',
    'FAQControllers@delete' => 'delete-faq',
    'FAQControllers@sort' => 'sort-faq',
    'FAQControllers@arrange' => 'sort-faq',
    'FAQControllers@charts' => 'charts-faq',
    'FAQControllers@uploadImage' => 'uploadImage-faq',
    'FAQControllers@deleteImage' => 'deleteImage-faq',

    'ChangeLogControllers@index' => 'list-changeLogs',
    'ChangeLogControllers@edit' => 'edit-changeLog',
    'ChangeLogControllers@update' => 'edit-changeLog',
    'ChangeLogControllers@fastEdit' => 'edit-changeLog',
    'ChangeLogControllers@add' => 'add-changeLog',
    'ChangeLogControllers@create' => 'add-changeLog',
    'ChangeLogControllers@delete' => 'delete-changeLog',
    'ChangeLogControllers@sort' => 'sort-changeLog',
    'ChangeLogControllers@arrange' => 'sort-changeLog',
    'ChangeLogControllers@charts' => 'charts-changeLog',
    'ChangeLogControllers@uploadImage' => 'uploadImage-changeLog',
    'ChangeLogControllers@deleteImage' => 'deleteImage-changeLog',

    'CentralTicketControllers@index' => 'list-tickets',
    'CentralTicketControllers@edit' => 'edit-ticket',
    'CentralTicketControllers@view' => 'view-ticket',
    'CentralTicketControllers@update' => 'edit-ticket',
    'CentralTicketControllers@fastEdit' => 'edit-ticket',
    'CentralTicketControllers@add' => 'add-ticket',
    'CentralTicketControllers@create' => 'add-ticket',
    'CentralTicketControllers@delete' => 'delete-ticket',
    'CentralTicketControllers@sort' => 'sort-ticket',
    'CentralTicketControllers@arrange' => 'sort-ticket',
    'CentralTicketControllers@charts' => 'charts-ticket',
    'CentralTicketControllers@uploadImage' => 'uploadImage-ticket',
    'CentralTicketControllers@deleteImage' => 'deleteImage-ticket',
    'CentralTicketControllers@addComment' => 'addComment-ticket',
    'CentralTicketControllers@updateComment' => 'updateComment-ticket',
    'CentralTicketControllers@deleteComment' => 'deleteComment-ticket',

    'DepartmentControllers@index' => 'list-departments',
    'DepartmentControllers@edit' => 'edit-department',
    'DepartmentControllers@update' => 'edit-department',
    'DepartmentControllers@fastEdit' => 'edit-department',
    'DepartmentControllers@add' => 'add-department',
    'DepartmentControllers@create' => 'add-department',
    'DepartmentControllers@delete' => 'delete-department',
    'DepartmentControllers@sort' => 'sort-department',
    'DepartmentControllers@arrange' => 'sort-department',
    'DepartmentControllers@charts' => 'charts-department',

    'ClientControllers@index' => 'list-clients',
    'ClientControllers@edit' => 'edit-client',
    'ClientControllers@view' => 'view-client',
    'ClientControllers@invLogin' => 'invisibleLogin-client',
    'ClientControllers@pinCodeLogin' => 'loginByPinCode-client',
    'ClientControllers@updateSettings' => 'updateChannelSettings-client',
    'ClientControllers@transferDays' => 'transferDays-client',
    'ClientControllers@update' => 'edit-client',
    'ClientControllers@fastEdit' => 'edit-client',
    'ClientControllers@add' => 'add-client',
    'ClientControllers@create' => 'add-client',
    'ClientControllers@delete' => 'delete-client',
    'ClientControllers@sort' => 'sort-client',
    'ClientControllers@arrange' => 'sort-client',
    'ClientControllers@charts' => 'charts-client',
    'ClientControllers@uploadImage' => 'uploadImage-client',
    'ClientControllers@deleteImage' => 'deleteImage-client',
  
    'InvoiceControllers@index' => 'list-invoices',
    'InvoiceControllers@edit' => 'edit-invoice',
    'InvoiceControllers@view' => 'view-invoice',
    'InvoiceControllers@update' => 'edit-invoice',
    'InvoiceControllers@fastEdit' => 'edit-invoice',
    'InvoiceControllers@delete' => 'delete-invoice',
    'InvoiceControllers@sort' => 'sort-invoice',
    'InvoiceControllers@arrange' => 'sort-invoice',
    'InvoiceControllers@charts' => 'charts-invoice',

    'CentralCategoryControllers@index' => 'list-categorys',
    'CentralCategoryControllers@edit' => 'edit-category',
    'CentralCategoryControllers@update' => 'edit-category',
    'CentralCategoryControllers@fastEdit' => 'edit-category',
    'CentralCategoryControllers@add' => 'add-category',
    'CentralCategoryControllers@create' => 'add-category',
    'CentralCategoryControllers@delete' => 'delete-category',
    'CentralCategoryControllers@sort' => 'sort-category',
    'CentralCategoryControllers@arrange' => 'sort-category',
    'CentralCategoryControllers@charts' => 'charts-category',

];
