<?php


return [
    
    'DashboardControllers@Dashboard' => 'general',
    'DashboardControllers@menu' => 'general',
    'DashboardControllers@changeLang' => 'general',
    'DashboardControllers@changeTheme' => 'general',
    'DashboardControllers@changeThemeToDefault' => 'general',
    'ProfileControllers@index' => 'general',
    'ProfileControllers@personalInfo' => 'general',
    'ProfileControllers@updatePersonalInfo' => 'general',
    'ProfileControllers@uploadImage' => 'general',
    'ProfileControllers@deleteImage' => 'general',
    'ProfileControllers@changePassword' => 'general',
    'ProfileControllers@postChangePassword' => 'general',
    'ProfileControllers@services' => 'general',

    'DashboardControllers@faqs' => 'general',
    'DashboardControllers@helpCenter' => 'general',
    'DashboardControllers@addRate' => 'general',

    'SubscriptionControllers@packages' => 'general',
    'SubscriptionControllers@updateSubscription' => 'general',
    'SubscriptionControllers@postUpdateSubscription' => 'general',
    'SubscriptionControllers@updateAddonStatus' => 'general',
    'SubscriptionControllers@updateQuotaStatus' => 'general',




    'WhatsappOrdersControllers@getOneOrder' => 'general',

    
    'SubscriptionControllers@checkout' => 'general',
    'SubscriptionControllers@postCheckout' => 'general',
    'SubscriptionControllers@completeOrder' => 'general',
    'SubscriptionControllers@pushInvoice' => 'general',
    'SubscriptionControllers@qrIndex' => 'general',
    'SubscriptionControllers@updateName' => 'general',
    'SubscriptionControllers@getQR' => 'general',
    'SubscriptionControllers@finishModID' => 'general',
    'SubscriptionControllers@editTemplate' => 'general',



    'ProfileControllers@paymentInfo' => 'paymentInfo',
    'ProfileControllers@postPaymentInfo' => 'paymentInfo',

    'ProfileControllers@taxInfo' => 'taxInfo',
    'ProfileControllers@postTaxInfo' => 'taxInfo',

    'ProfileControllers@notifications' => 'notifications',
    'ProfileControllers@postNotifications' => 'notifications',

    'ProfileControllers@offers' => 'offers',
    'ProfileControllers@postOffers' => 'offers',

    'ProfileControllers@extraQuotas' => 'extraQuotas',
    'ProfileControllers@postExtraQuotas' => 'extraQuotas',

    'ProfileControllers@addons' => 'addons',
    'ProfileControllers@postAddons' => 'addons',

    

    'ProfileControllers@subscription' => 'subscription',
    'ProfileControllers@screenshot' => 'subscription',
    'ProfileControllers@reconnect' => 'subscription',
    'ProfileControllers@closeConn' => 'subscription',
    'ProfileControllers@sync' => 'subscription',
    'ProfileControllers@read' => 'subscription',

    'ProfileControllers@apiSetting' => 'apiSetting',
    'ProfileControllers@apiGuide' => 'apiGuide',
    'ProfileControllers@webhookSetting' => 'webhookSetting',
    'ProfileControllers@postWebhookSetting' => 'webhookSetting',


    'ApiModsControllers@msgsArchive'  => 'list-messages-archive',
    'ApiModsControllers@report'  =>  'list-groupNumberReports',
    'ApiModsControllers@index'  =>  'list-statuses',

    'ContactsControllers@index' => 'list-contacts',
    'ContactsControllers@edit' => 'edit-contact',
    'ContactsControllers@update' => 'edit-contact',
    'ContactsControllers@fastEdit' => 'edit-contact',
    'ContactsControllers@add' => 'add-contact',
    'ContactsControllers@create' => 'add-contact',
    'ContactsControllers@delete' => 'delete-contact',
    'ContactsControllers@sort' => 'sort-contact',
    'ContactsControllers@arrange' => 'sort-contact',
    'ContactsControllers@charts' => 'charts-contact',
    'ContactsControllers@downloadContacts' => 'export-contacts',

    'GroupNumbersControllers@index' => 'list-group-numbers',
    'GroupNumbersControllers@edit' => 'edit-group-number',
    'GroupNumbersControllers@update' => 'edit-group-number',
    'GroupNumbersControllers@fastEdit' => 'edit-group-number',
    'GroupNumbersControllers@add' => 'add-group-number',
    'GroupNumbersControllers@create' => 'add-group-number',
    'GroupNumbersControllers@delete' => 'delete-group-number',
    'GroupNumbersControllers@sort' => 'sort-group-number',
    'GroupNumbersControllers@arrange' => 'sort-group-number',
    'GroupNumbersControllers@charts' => 'charts-group-number',
    'GroupNumbersControllers@addGroupNumbers' =>'add-number-to-group',
    'GroupNumbersControllers@postAddGroupNumbers' =>'add-number-to-group',

    'CategoryControllers@index' => 'list-categories',
    'CategoryControllers@edit' => 'edit-category',
    'CategoryControllers@update' => 'edit-category',
    'CategoryControllers@fastEdit' => 'edit-category',
    'CategoryControllers@add' => 'add-category',
    'CategoryControllers@create' => 'add-category',
    'CategoryControllers@delete' => 'delete-category',
    'CategoryControllers@sort' => 'sort-category',
    'CategoryControllers@arrange' => 'sort-category',
    'CategoryControllers@charts' => 'charts-category',

    'RepliesControllers@index' => 'list-replies',
    'RepliesControllers@edit' => 'edit-reply',
    'RepliesControllers@update' => 'edit-reply',
    'RepliesControllers@fastEdit' => 'edit-reply',
    'RepliesControllers@add' => 'add-reply',
    'RepliesControllers@create' => 'add-reply',
    'RepliesControllers@delete' => 'delete-reply',
    'RepliesControllers@sort' => 'sort-reply',
    'RepliesControllers@arrange' => 'sort-reply',
    'RepliesControllers@charts' => 'charts-reply',

    'TemplatesControllers@index' => 'list-templates',
    'TemplatesControllers@edit' => 'edit-template',
    'TemplatesControllers@update' => 'edit-template',
    'TemplatesControllers@fastEdit' => 'edit-template',
    'TemplatesControllers@add' => 'add-template',
    'TemplatesControllers@create' => 'add-template',
    'TemplatesControllers@delete' => 'delete-template',
    'TemplatesControllers@sort' => 'sort-template',
    'TemplatesControllers@arrange' => 'sort-template',
    'TemplatesControllers@charts' => 'charts-template',
    
    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@sort' => 'sort-user',
    'UsersControllers@arrange' => 'sort-user',
    'UsersControllers@charts' => 'charts-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',
    'GroupsControllers@sort' => 'sort-group',
    'GroupsControllers@arrange' => 'sort-group',
    'GroupsControllers@charts' => 'charts-group',

    'TicketControllers@index' => 'list-tickets',
    'TicketControllers@edit' => 'edit-ticket',
    'TicketControllers@view' => 'view-ticket',
    'TicketControllers@update' => 'edit-ticket',
    'TicketControllers@fastEdit' => 'edit-ticket',
    'TicketControllers@add' => 'add-ticket',
    'TicketControllers@create' => 'add-ticket',
    'TicketControllers@delete' => 'delete-ticket',
    'TicketControllers@sort' => 'sort-ticket',
    'TicketControllers@arrange' => 'sort-ticket',
    'TicketControllers@charts' => 'charts-ticket',
    'TicketControllers@uploadImage' => 'uploadImage-ticket',
    'TicketControllers@deleteImage' => 'deleteImage-ticket',
    'TicketControllers@addComment' => 'addComment-ticket',
    'TicketControllers@updateComment' => 'updateComment-ticket',
    'TicketControllers@deleteComment' => 'deleteComment-ticket',

    'UserStorageControllers@index' => 'list-storage',
    'UserStorageControllers@bots' => 'list-storage',
    'UserStorageControllers@groupMsgs' => 'list-storage',
    'UserStorageControllers@chats' => 'list-storage',
    'UserStorageControllers@getByTypeAndId' => 'list-storage',
    'UserStorageControllers@removeByTypeAndId' => 'delete-storage',
    'UserStorageControllers@removeChatFile' => 'delete-storage',

    'TenantInvoiceControllers@index' => 'list-invoices',
    'TenantInvoiceControllers@view' => 'view-invoice',
    'TenantInvoiceControllers@sort' => 'sort-invoice',
    'TenantInvoiceControllers@arrange' => 'sort-invoice',
    'TenantInvoiceControllers@charts' => 'charts-invoice',
    'TenantInvoiceControllers@checkout' => 'pay-invoice',
    'TenantInvoiceControllers@pushInvoice' => 'pay-invoice',


    // 'SallaControllers@customers' => 'salla-customers',
    // 'SallaControllers@products' => 'salla-products',
    // 'SallaControllers@orders' => 'salla-orders',
    // 'SallaControllers@reports' => 'salla-reports',
    // 'SallaControllers@templates' => 'salla-templates',
    // 'SallaControllers@templatesEdit' => 'edit-salla-template',
    // 'SallaControllers@templatesUpdate' => 'edit-salla-template',
    // 'ProfileControllers@updateSalla' => 'updateSalla',
    
    // 'ProfileControllers@updateZid' => 'updateZid',
    // 'ZidControllers@customers' => 'zid-customers',
    // 'ZidControllers@products' => 'zid-products',
    // 'ZidControllers@orders' => 'zid-orders',
    // 'ZidControllers@reports' => 'zid-reports',
    // 'ZidControllers@templates' => 'zid-templates',
    // 'ZidControllers@templatesEdit' => 'edit-zid-template',
    // 'ZidControllers@templatesUpdate' => 'edit-zid-template',
    
    // 'GroupMsgsControllers@index' => 'list-group-messages',
    // 'GroupMsgsControllers@add' => 'add-group-message' ,
    // 'GroupMsgsControllers@create' => 'add-group-message',
    // 'GroupMsgsControllers@view' => 'add-group-message',
    // 'GroupMsgsControllers@charts' => 'charts-group-message',
    // 'GroupMsgsControllers@uploadImage' => 'uploadImage-group-message',

    // 'BotControllers@index' => 'list-bots',
    // 'BotControllers@edit' => 'edit-bot',
    // 'BotControllers@update' => 'edit-bot',
    // 'BotControllers@fastEdit' => 'edit-bot',
    // 'BotControllers@add' => 'add-bot',
    // 'BotControllers@create' => 'add-bot',
    // 'BotControllers@copy' => 'copy-bot',
    // 'BotControllers@delete' => 'delete-bot',
    // 'BotControllers@sort' => 'sort-bot',
    // 'BotControllers@arrange' => 'sort-bot',
    // 'BotControllers@charts' => 'charts-bot',
    // 'BotControllers@uploadImage' => 'uploadImage-bot',
    // 'BotControllers@deleteImage' => 'deleteImage-bot',

    // 'LiveChatControllers@index' => 'list-livechat',
    

  
];
