<?php

return [
      'configs' => [
            [
                  'name' => 'default',
                  'signing_secret' => '',
                  'signature_header_name' => 'Signature',
                  'signature_validator' => App\Handler\WebhookSignature::class,
                  'webhook_profile' => \Spatie\WebhookClient\WebhookProfile\ProcessEverythingWebhookProfile::class,
                  'webhook_response' => \Spatie\WebhookClient\WebhookResponse\DefaultRespondsTo::class,
                  'webhook_model' => \Spatie\WebhookClient\Models\WebhookCall::class,
                  'process_webhook_job' => App\Handler\MessagesWebhook::class,
            ],
            [
                  'name' => 'Zid',
                  'signing_secret' => '',
                  'signature_header_name' => 'Signature',
                  'signature_validator' => App\Handler\WebhookSignature::class,
                  'webhook_profile' => \Spatie\WebhookClient\WebhookProfile\ProcessEverythingWebhookProfile::class,
                  'webhook_response' => \Spatie\WebhookClient\WebhookResponse\DefaultRespondsTo::class,
                  'webhook_model' => \Spatie\WebhookClient\Models\WebhookCall::class,
                  'process_webhook_job' => App\Handler\ZidWebhook::class,
            ],
            [
                  'name' => 'Salla',
                  'signing_secret' => '',
                  'signature_header_name' => 'Signature',
                  'signature_validator' => App\Handler\WebhookSignature::class,
                  'webhook_profile' => \Spatie\WebhookClient\WebhookProfile\ProcessEverythingWebhookProfile::class,
                  'webhook_response' => \Spatie\WebhookClient\WebhookResponse\DefaultRespondsTo::class,
                  'webhook_model' => \Spatie\WebhookClient\Models\WebhookCall::class,
                  'process_webhook_job' => App\Handler\SallaWebhook::class,
            ],
            [
                  'name' => 'Salla2',
                  'signing_secret' => '',
                  'signature_header_name' => 'Signature',
                  'signature_validator' => App\Handler\WebhookSignature::class,
                  'webhook_profile' => \Spatie\WebhookClient\WebhookProfile\ProcessEverythingWebhookProfile::class,
                  'webhook_response' => \Spatie\WebhookClient\WebhookResponse\DefaultRespondsTo::class,
                  'webhook_model' => \Spatie\WebhookClient\Models\WebhookCall::class,
                  'process_webhook_job' => App\Handler\SallaWebhook2::class,
            ],
            [
                  'name' => 'Official',
                  'signing_secret' => 'OfficialSaysHello',
                  'signature_header_name' => 'Signature',
                  'signature_validator' => App\Handler\OfficialWebhookSignature::class,
                  'webhook_profile' => \Spatie\WebhookClient\WebhookProfile\ProcessEverythingWebhookProfile::class,
                  'webhook_response' => \Spatie\WebhookClient\WebhookResponse\DefaultRespondsTo::class,
                  'webhook_model' => \Spatie\WebhookClient\Models\WebhookCall::class,
                  'process_webhook_job' => App\Handler\OfficialWebhook::class,
            ],
      ],
];
